// Seed data for the local SQLite database.

export const PORTERS = [
  {
    id: "p1",
    name: "Ramesh Kumar",
    avatar: "RK",
    rating: 4.9,
    reviews: 312,
    price: 80,
    distance: "Platform 3",
    available: true,
    experience: "5 yrs",
    completedJobs: 1240,
    badge: "Top Rated",
  },
  {
    id: "p2",
    name: "Suresh Yadav",
    avatar: "SY",
    rating: 4.7,
    reviews: 198,
    price: 60,
    distance: "Platform 1",
    available: true,
    experience: "3 yrs",
    completedJobs: 780,
    badge: "Verified",
  },
  {
    id: "p3",
    name: "Mohan Singh",
    avatar: "MS",
    rating: 4.8,
    reviews: 256,
    price: 70,
    distance: "Platform 5",
    available: true,
    experience: "4 yrs",
    completedJobs: 960,
    badge: "Verified",
  },
  {
    id: "p4",
    name: "Dinesh Patel",
    avatar: "DP",
    rating: 4.6,
    reviews: 142,
    price: 55,
    distance: "Platform 2",
    available: false,
    experience: "2 yrs",
    completedJobs: 430,
    badge: null,
  },
];

export const BOOKINGS = [
  {
    id: "BK001",
    passenger: "Arjun Mehta",
    porter: "Ramesh Kumar",
    from: "New Delhi Railway Station",
    to: "Exit Gate B",
    status: "completed",
    amount: 80,
    date: "2025-01-15",
    pnr: "4521876543",
    rating: 5,
  },
  {
    id: "BK002",
    passenger: "Priya Sharma",
    porter: "Suresh Yadav",
    from: "Mumbai CST",
    to: "Taxi Stand",
    status: "active",
    amount: 60,
    date: "2025-01-16",
    pnr: "7834521098",
    rating: null,
  },
  {
    id: "BK003",
    passenger: "Vikram Nair",
    porter: "Mohan Singh",
    from: "Bangalore City Junction",
    to: "Platform 4",
    status: "pending",
    amount: 70,
    date: "2025-01-16",
    pnr: "3219876540",
    rating: null,
  },
  {
    id: "BK004",
    passenger: "Sneha Reddy",
    porter: "Ramesh Kumar",
    from: "Chennai Central",
    to: "Parking Lot",
    status: "completed",
    amount: 90,
    date: "2025-01-14",
    pnr: "9087654321",
    rating: 5,
  },
];

export const PORTER_JOBS = [
  {
    id: "J001",
    passenger: "Arjun Mehta",
    from: "Platform 8",
    to: "Exit Gate A",
    luggage: "2 bags",
    amount: 80,
    status: "incoming",
    time: "2 min ago",
  },
  {
    id: "J002",
    passenger: "Priya Sharma",
    from: "Platform 3",
    to: "Taxi Stand",
    luggage: "1 trolley",
    amount: 60,
    status: "incoming",
    time: "5 min ago",
  },
];

export const EARNINGS = {
  today: 480,
  week: 2840,
  month: 11200,
  totalJobs: 1240,
  rating: 4.9,
  completionRate: 97,
};

export const STATS = {
  totalPassengers: "50,000+",
  totalPorters: "2,000+",
  citiesCovered: "120+",
  avgRating: "4.8",
};

export const STATIONS = [
  "New Delhi Railway Station",
  "Mumbai CST",
  "Bangalore City Junction",
  "Chennai Central",
  "Howrah Junction",
  "Hyderabad Deccan",
  "Pune Junction",
  "Ahmedabad Junction",
];
